### ISSUE TITLE
Use of deprecated config.set_request_property causes AttributeError with pyramid >= 1.10

### ISSUE THREAD

**Issue by jjmurre** [Pylons/pyramid_ldap#26]
https://github.com/Pylons/pyramid_ldap/blob/69658b531739a106790da26d4d031d45e5eba558/pyramid_ldap/__init__.py#L304

Should now be configurator.add_request_method, according to pyramid's list of backwards incompatibilities for 1.10

**Comment by nutjob4life** [comment]
For those who came here by way of a search engine and are wondering what to do:

- Try downgrading Pyramid to 1.9.4 in your `setup.py`, `requirements.txt`, `buildout.cfg`, etc.
- Or, use [pyramid_ldap3](https://pypi.org/project/pyramid-ldap3/) instead of `pyramid_ldap`
- Or wait for `pyramid_ldap` 0.3.2 or later to be released 😉

**Comment by digitalresistor** [comment]
This was fixed in #33.
